### PR TITLE
Added Icon MCU support

### PR DESCRIPTION
**Pull request by ericahrens**

### CODE REVIEW

**Review by abique — COMMENTED** [review]
Did you just re-format the launchpad pro step sequencer or did you actually change something in there?

Sorry but I'm not a big fan of the `if (cond) return;` in one line, could you restore the old style please?

Thanks for the pull request.

**Comment by ericahrens** [comment]
> Did you just re-format the launchpad pro step sequencer or did you actually change something in there?
Oops. Did not intend to change that File at all. Accidentally hit it because class name is similar to my own StepSequencer.
Will revert.

**Comment by ericahrens** [comment]
> Sorry but I'm not a big fan of the `if (cond) return;` in one line, could you restore the old style please?

Btw. just looking at the code of StepeSequenceMode.java. There are a bunch of single line blocks.
My automatic formatter is set in such a way that every block statement get's a { }, also the single line ones. That's what I prefer.
Anyway, the file is back to it's original state.

**Comment by abique** [comment]
By the way the pull request was against api-16, was your change meant for api-15?

**Comment by ericahrens** [comment]
> By the way the pull request was against api-16, was your change meant for api-15?

It was still on my own api-15 branch but was meant for api-16. So, all good!

**Pull request merged**
