### PR TITLE
Enhance User Interaction with Encoder Setup and Display Update in ArturiaKeylabMkII

### PR DESCRIPTION
**Pull request by mikefaille**
- Imported RemoteControl for encoder configuration.
- Added setupEncoders() to initialize encoder value observers.
- Added updateEncoderDisplay() to show track name and encoder parameter info.
- Initialized encoders in init() method.

### CODE REVIEW

**Comment by bitwig-thomas** [comment]
Hey, thank you for your contribution! I like the idea. We will review this internally and provide feedback soon.

**Comment by mikefaille** [comment]
Thank you ! I would like to have it upstream and share it to every Bitwig users !

**Comment by bitwig-thomas** [comment]
Hey, we decided to pick up the idea, but go with a slightly different implementation. You can find our version here: https://github.com/bitwig/bitwig-extensions/pull/76.

**Comment by mikefaille** [comment]
I've tested the controller implementation in PR #76 and l'm impressed with the results. Really happy with how it turned out! 

Two quick questions:

1. Does Bitwig offer any recognition, like a temporary license, for contributions like this? 
2. Who can I contact to discuss potential career opportunities at Bitwig?

Thanks for this collaborative experience!

**Comment by bitwig-thomas** [comment]
I've sent you an email.

**Pull request closed without merging**
