### PR TITLE
Added Mackie Control but disable for now in extension list.

### PR DESCRIPTION
**Pull request by ericahrens**

### CODE REVIEW

**Comment by abique** [comment]
Thank you! :)

**Comment by abique** [comment]
It does not compile. Did you forget to check in some files?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project bitwig-extensions: Compilation failure: Compilation failure: 
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[42,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[43,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[44,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[45,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/MackieMcuProExtension.java:[34,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[27,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[28,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[29,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[30,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingParameterBankDisplayBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingParameterBankDisplayBinding.java:[12,76] error: cannot find symbol
[ERROR]   symbol: class RingDisplay
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderParameterBankBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderParameterBankBinding.java:[7,70] error: cannot find symbol
[ERROR]   symbol: class MotorFader
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[103,64] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ParameterPage
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[108,59] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ParameterPage
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[113,81] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class ParameterPage
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayNameBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayNameBinding.java:[7,71] error: cannot find symbol
[ERROR]   symbol: class DisplayNameTarget
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/devices/ParameterPage.java:[122,83] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class ParameterPage
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayValueBinding.java:[3,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayValueBinding.java:[6,72] error: cannot find symbol
[ERROR]   symbol: class DisplayValueTarget
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayValueBinding.java:[9,58] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class AbstractDisplayValueBinding<T>
[ERROR]   where T is a type-variable:
[ERROR]     T extends Object declared in class AbstractDisplayValueBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/AbstractDisplayNameBinding.java:[10,57] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class AbstractDisplayNameBinding<T>
[ERROR]   where T is a type-variable:
[ERROR]     T extends Object declared in class AbstractDisplayNameBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderParameterBankBinding.java:[9,68] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class FaderParameterBankBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingParameterBankDisplayBinding.java:[17,74] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class RingParameterBankDisplayBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[64,15] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[65,15] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[67,7] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[68,7] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[239,1] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[255,1] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[259,1] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[263,1] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayStringValueBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderBinding.java:[7,53] error: cannot find symbol
[ERROR]   symbol: class MotorFader
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingDisplayBinding.java:[5,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingDisplayBinding.java:[8,59] error: cannot find symbol
[ERROR]   symbol: class RingDisplay
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayNameBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayNameBinding.java:[8,59] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class DisplayNameBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/RingDisplayBinding.java:[12,57] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class RingDisplayBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/FaderBinding.java:[11,51] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class FaderBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayStringValueBinding.java:[8,66] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class DisplayStringValueBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/remoteconsole/DisabledRemoteConsole.java:[3,46] error: cannot find symbol
[ERROR]   symbol: class RemoteConsole
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayDoubleValueBinding.java:[4,54] error: package com.bitwig.extensions.controllers.mackie.target does not exist
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/bindings/DisplayDoubleValueBinding.java:[10,74] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class DisplayDoubleValueBinding
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[64,49] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[65,48] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[67,47] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[68,45] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[151,27] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[152,25] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[161,25] error: cannot find symbol
[ERROR]   symbol:   class DisplayValueTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[162,24] error: cannot find symbol
[ERROR]   symbol:   class DisplayNameTarget
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[208,13] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[212,13] error: cannot find symbol
[ERROR]   symbol:   class RingDisplay
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/layer/ChannelSection.java:[553,13] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class ChannelSection
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/MackieMcuProExtension.java:[223,8] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class MackieMcuProExtension
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/controllers/mackie/MackieMcuProExtension.java:[223,45] error: cannot find symbol
[ERROR]   symbol:   class MotorFader
[ERROR]   location: class MackieMcuProExtension
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/remoteconsole/DisabledRemoteConsole.java:[5,1] error: method does not override or implement a method from a supertype
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/remoteconsole/DisabledRemoteConsole.java:[9,1] error: method does not override or implement a method from a supertype
[ERROR] /home/abique/develop/bitwig/bitwig-extensions/src/main/java/com/bitwig/extensions/remoteconsole/DisabledRemoteConsole.java:[13,1] error: method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by ericahrens** [comment]
Hi Alex,
Sorry about that. I can see that the package
*com.bitwig.extesnsions.controllers.mackie.target* is somehow missing in
api-13, same thing for the api-14. Not quite sure how that happened. I am
pretty sure I staged and committed everything that needed to be. I wonder
if my Eclipse IDE misled me.
Anyway, as I am not at home but at my office, it will have to wait until
this evening to be fixed.
Again, sorry about that, next time I will double check on github.
Best,
Eric

Am Mo., 21. Juni 2021 um 09:22 Uhr schrieb Alexandre Bique <
***@***.***>:

**Comment by abique** [comment]
Hi Eric,
Don't worry, it can wait for this evening.
This is also our fault: we should have a pre-merge automated test bot.
Cheers,
Alex

**Comment by ericahrens** [comment]
Hi Alex,
For some weird reason Eclipse did not recognize that a package with the
name .target should be considered for staging. Somehow I suspect this might
be an Eclipse bug as the name "target" also has a special meaning in
Eclipse (i.e. Target Platform etc). Anyway, I renamed the package to
targets and now it's there and it should compile again.
Cheers, Eric

Am Mo., 21. Juni 2021 um 09:45 Uhr schrieb Alexandre Bique <
***@***.***>:

**Pull request merged**
